title = 'Create a tui for ticket'
status = 'Closed'
number = 4
description = '''
Currently ticket is all cli driven. The experience isn't the worst, but
the end goal has always been to get the user to be able to have a nice
in terminal experience, almost as if they never left GitHub. A basic
tui that allows one to read and comment on issues will suffice to close
this ticket.
'''
